collection_queries={
    'INSERT_USER_COLLECTION': "INSERT INTO COLLECTION (NAME, IS_GLOBAL) VALUES (%s, '0')",
    'INSERT_GLOBAL_COLLECTION': "INSERT INTO COLLECTION (NAME, IS_GLOBAl) VALUES (%s, '1')",
    'GET_GLOBAL_COLLECTIONS': "SELECT NAME FROM COLLECTION WHERE IS_GLOBAL='1'",
    'UPDATE_COLLECTION': "UPDATE COLLECTION SET IS_ACTIVE='0' WHERE ID=%s"
}

book_collection_queries={
    'INSERT_COLLECTION': 'INSERT INTO BOOK_COLLECTION (COLLECTION_ID, BOOK_ID, CUSTOMER_ID) VALUES (%s, %s, %s)',
    'GET_COLLECTION_BY_USER': 'SELECT C.NAME AS COLLECTION_NAMES FROM COLLECTION AS C JOIN BOOK_COLLECTION AS BK ON BK.COLLECTION_ID = C.ID JOIN USERS AS U ON BK.CUSTOMER_ID = U.ID JOIN BOOKS AS B ON BK.BOOK_ID = B.ID WHERE BK.CUSTOMER_ID=%s',
    'DELETE_BOOK_FROM_COLLECTION': "UPDATE BOOK_COLLECTION SET IS_ACTIVE='0' WHERE ID=%s",
    'GET_BOOKS_FROM_COLLECTION' : 'SELECT B.TITLE AS BOOKS FROM BOOKS AS B JOIN BOOK_COLLECTION AS BK ON BK.BOOK_ID = B.ID WHERE BK.COLLECTION_ID=%s',
    'FIND_COLLECTION': "SELECT CUSTOMER_ID FROM BOOK_COLLECTION WHERE CUSTOMER_ID=%s"
}