user_queries={
    "INSERT_USER": "INSERT INTO USERS(USER_ID,NAME,USERNAME,PASSWORD,EMAIL,PHONE_NUMBER,DOB,ROLE) VALUES(%s, %s, %s, %s, %s, %s, %s, %s)",
    "GET_USERS": "SELECT NAME, USERNAME, EMAIL, PHONE_NUMBER, DOB, ROLE FROM USERS",
    "GET_USER" : "SELECT NAME, USERNAME, EMAIL, PHONE_NUMBER, DOB, ROLE FROM USERS WHERE USERNAME = %s",
    "UPDATE_USER": "UPDATE USERS SET USERNAME = %s, PASSWORD= %s, PHONE_NUMBER= %s WHERE ID = %s",
    "DELETE_USER": "UPDATE USERS SET IS_ACTIVE='0' WHERE USERNAME = %s"
}

